version: '2'
services:
  redis:
    build: ./docker/redis

  couch:
    build: ./docker/couchdb
    ports:
      - "49162:5984"

  hookio:
    build: .
    command: /src/bin/docker/wait redis couch worker0 balancer -c node /src/bin/services/web
    depends_on:
      - "redis"
      - "couch"
    #ports:
    #  - "11000"

  balancer:
    #build: .
    image: "hookio_hookio"
    command: /src/bin/docker/wait redis -c node /src/bin/services/load-balancer
    ports:
      - "80:9999"
    depends_on:
      - "hookio"

  worker0:
    #build: .
    image: "hookio_hookio"
    command: /src/bin/docker/wait redis couch -c node /src/bin/services/worker
    privileged: true
    ports:
      - "49161:10000"
    depends_on:
      - "hookio"

  setup:
    #build: .
    image: "hookio_hookio"
    command: /src/bin/docker/wait couch -c /src/bin/docker/initialize
    depends_on:
      - "hookio"
