redis:
  build: ./docker/redis

couch:
  build: ./docker/couchdb
  ports:
    - "49162:5984"

hookio:
  build: .
  command: /src/bin/docker-wait node /src/bin/services/web
  ports:
    - "80:9999"
  links:
    - "redis:redis"
    - "couch:couch"
    - "worker0:worker0"

worker0:
  build: .
  command: /src/bin/docker-wait node /src/bin/services/worker
  privileged: true
  ports:
    - "49161:10000"
  links:
    - "redis:redis"
    - "couch:couch"

setup:
  build: .
  command: /src/bin/docker-wait /src/config/couchdb/create_admin.sh
  links:
    - "couch:couch"

install_default_hooks:
  build: .
  command: /src/bin/docker-wait node /src/scripts/install/add-default-hooks.js
  links:
    - "couch:couch"
    - "redis:redis"
    - "hookio:hookio"
